name: Run Win11 and Expose

on: [push]

jobs:
  build-win11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install docker
        run: sudo apt-get update && sudo apt-get install docker-compose
      - name: start win11
        run: docker-compose up -d
      - name: install ngrok
        run: |
          curl -sSL https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
            && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list \
            && sudo apt-get update \
            && sudo apt-get install -y ngrok
      - name: Expose with Ngrok
        run: |
          ngrok config add-authtoken ${{secrets.NGROK_TOKEN}}
          ngrok http 8006
